# Generated by Django 4.0.6 on 2023-02-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='telp',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
